---
- name: Updating apt
  apt:
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Installing nginx
  apt:
    name: nginx
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Installing nginx
  yum: 
    name: nginx
    state: present
  become: yes
  when: ansible_os_family == "Redhat"