apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myuser
spec:
# Use command cat myuser.csr | base64 | tr -d "\n"
  request: long_csr_base64_encoded 
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
