apiVersion: apps/v1
kind: Deployment
metadata:
    name: local-deploy
    labels:
        app: local
        tier: backend
spec:
    replicas: 2
    template:
        metadata:
            name: local
            labels:
                app: local
                tier: backend
        spec:
            containers:
                - name: local
                  image: kube-poc:local
                  imagePullPolicy: Never
                  env:
                      - name: CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: client_id
                      - name: SCOPE
                        valueFrom:
                            configMapRef:
                                name: config
                                key: scope

    selector:
        matchLabels:
            app: local
            tier: backend
