apiVersion: v1
kind: Pod
metadata: 
  name: redis-db-pod
  labels:
    name: redis-db-pod
    app: demo-voting-app
spec:
  containers: 
    - name: redis
      image: redis
      ports:
        - containerPort: 6379 